services:
  spring-app:
    image: interview:0.0.1-SNAPSHOT
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mydatabase
    depends_on:
      - database

  database:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    ports:
      - '3306'
